module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  testMatch: [
    '**/*.publisher.spec.ts',
    '**/*.subscriber.spec.ts',
    '**/*.processor.spec.ts',
    '**/*.service.spec.ts',
    '**/*.controller.spec.ts',
    '**/*.utils.spec.ts',
    '**/*.interceptor.spec.ts',
    '**/*.filter.spec.ts',
    '**/*.guard.spec.ts',
    '**/*.decorator.spec.ts',
    '**/*.pipe.spec.ts',
    '**/*.validator.spec.ts',
    '**/*.middleware.spec.ts',
    '**/*.accessor.spec.ts',
    '**/*.gateway.spec.ts',
    '**/*.exception.spec.ts',
    '**/*.config.spec.ts',
  ],
  testPathIgnorePatterns: [
    '/common/',
    '/health/',
    '/db/',
    '/node_modules/',
    '/config/',
    '/events/',
  ],
  coveragePathIgnorePatterns: [
    '/common/',
    String.raw`/config/.*\.index\.ts`,
    '/health/',
    '/db/',
    '/node_modules/',
    '/events/',
  ],
  collectCoverage: true,
  coverageDirectory: 'coverage',
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
  },
};
